sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
# See https://github.com/exasol/redshift-virtual-schema/issues/7
#      - integration_tests
#      - udf_coverage
build:
  runnerOs: ubuntu-latest
  freeDiskSpace: false
# See https://github.com/exasol/redshift-virtual-schema/issues/7
#  exasolDbVersions:
#    - "8.34.0"
#    - "7.1.30"
excludes:
linkReplacements:
