language: java

matrix:
  include:
    - jdk: openjdk11

addons:
  sonarcloud:
    organization: exasol

install:
  - travis_retry mvn dependency:resolve

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:prepare-agent-integration verify sonar:sonar -Dsonar.login=${SONAR_TOKEN}

cache:
  directories:
    - "$HOME/.m2"
